__cmd() {
  command -v $1 >/dev/null
}
# ALIASES
git config --global alias.a 'add .'
git config --global alias.addp 'add -p'
git config --global alias.ai 'add -i'
git config --global alias.ap 'a -p'
git config --global alias.b 'branch'
git config --global alias.back 'co backend'
git config --global alias.db 'b -D'
git config --global alias.bm 'b --merged'
git config --global alias.bnm 'branch --no-merged'
git config --global alias.br 'branch -a'
git config --global alias.brv 'br -vv'
git config --global alias.bv 'b -vv'
git config --global alias.c 'commit'
git config --global alias.ca 'c -a'
git config --global alias.cam 'c -am'
git config --global alias.cb 'co -b'
git config --global alias.cc 'c --amend'
git config --global alias.cca 'cc -a'
git config --global alias.ccm 'cc -m'
git config --global alias.ce 'c --allow-empty'
git config --global alias.cei 'cem "Initial commit"'
git config --global alias.cem 'ce -m'
git config --global alias.cl 'clone'
git config --global alias.cm 'c -m'
git config --global alias.cmi 'cm "Initial commit"'
git config --global alias.co 'checkout'
git config --global alias.cod 'cb develop'
git config --global alias.con 'config'
git config --global alias.count 'rev-list --all --count'
git config --global alias.d 'diff'
git config --global alias.di 'diff --no-index'
git config --global alias.ds 'd --cached'
git config --global alias.dss 'ds --stat'
git config --global alias.dtag 'tag -d'
git config --global alias.dv 'co develop'
git config --global alias.f 'fetch'
git config --global alias.fa 'fetch --all'
git config --global alias.ff 'merge --ff-only'
git config --global alias.fix 'push -f'
git config --global alias.front 'co frontend'
git config --global alias.ftags 'fetch -t'
git config --global alias.i 'init'
git config --global alias.l 'log --oneline'
git config --global alias.la 'log --all'
git config --global alias.list 'sa'
git config --global alias.ll 'show -q'
git config --global alias.llp 'log -1 -p'
git config --global alias.lls 'log -1 --stat'
git config --global alias.lo 'log --oneline'
git config --global alias.logp 'log -p'
git config --global alias.logs 'log --stat'
git config --global alias.lp 'log -p'
git config --global alias.ls 'l --stat'
git config --global alias.lsa 'ls --all'
git config --global alias.m 'merge'
git config --global alias.ma 'm --abort'
git config --global alias.main '! git co main || git co master'
git config --global alias.mb 'b -m'
git config --global alias.mkdev 'cb develop'
git config --global alias.mm 'm -m'
git config --global alias.mnf 'merge --no-ff'
git config --global alias.mnfm 'mnf -m'
git config --global alias.ms 'squash'
git config --global alias.p 'pull'
git config --global alias.pa 'p --all'
git config --global alias.ptags 'push --tags'
git config --global alias.pop 'stash pop'
git config --global alias.pusha 'push --all'
git config --global alias.pushall 'push --all'
git config --global alias.r 'remote'
git config --global alias.ra 'r add'
git config --global alias.rb 'b --remotes'
git config --global alias.res 'restore'
git config --global alias.rr 'r remove'
git config --global alias.rrm 'r remove'
git config --global alias.rs 'remote -v'
git config --global alias.stat 'status'
git config --global alias.s 'status -s'
git config --global alias.sa 's -uall'
git config --global alias.sco 'sparse-checkout'
git config --global alias.sl 'shortlog'
git config --global alias.squash 'm --squash'
git config --global alias.ss 'd --stat'
git config --global alias.st 'stash'
git config --global alias.stl 'st list'
git config --global alias.stm 'st push -m'
git config --global alias.sub 'submodule'
git config --global alias.t 'log --oneline --graph'
git config --global alias.ta 'log --graph --oneline --all'
git config --global alias.tags 'log --oneline --tags --no-walk'
git config --global alias.tap 'ta -p'
git config --global alias.tas 'ta --stat'
git config --global alias.timeline 'log --graph --format="%C(yellow)%h%C(reset) %C(bold green)(%ar) %C(bold dim cyan)%an %C(reset)%s"'
git config --global alias.time 'timeline'
git config --global alias.times 'time --all'
git config --global alias.tm 't master'
git config --global alias.tmp 'tm -p'
git config --global alias.tms 'tm --stat'
git config --global alias.tp 't -p'
git config --global alias.tree 'log --oneline --graph --all'
git config --global alias.ts 't --stat'
git config --global alias.update '!git f; git p'
git config --global alias.wt 'worktree'
# CORE
#git config --global core.autocrlf input
git config --global core.safecrlf warn
__cmd nvim && git config --global core.editor nvim || git config --global core.editor vim
# INIT
git config --global init.defaultbranch main
# BRANCH
git config --global branch.autoSetupMerge simple
# PUSH
git config --global push.default upstream
# CYGWIN
if [[ `uname` == *CYGWIN* ]]; then
  if [ -f ~/.zsh_cygwin ]; then
    git config --global core.autocrlf true
  fi
fi
