glab alias set ssh 'ssh-key'
glab alias set gpg 'gpg-key'
glab alias set rm 'repo delete'
glab alias set sync 'repo sync'
glab alias set show 'repo edit --visibility public'
glab alias set hide 'repo edit --visibility private'
glab alias set view 'repo view -w'
glab alias set repos 'repo list'
glab alias set info 'repo view'
glab alias set default 'repo set-default'
glab alias set fork 'repo fork'
